import {
  faCalendar,
  faPager,
  faPaste,
  faCoffee,
  faCamera,
  faHeart,
  faEnvelope,
  faStar,
  faSmile,
  faSun,
  faMoon,
  faPlane,
  faBicycle,
  faCar,
  faBus,
  faTrain,
  faShip,
  faTruck,
  faMotorcycle,
  faCircleHalfStroke,
  faCircle,
  faChevronRight,
  faChevronLeft,
  faCheckCircle,
} from "@fortawesome/free-solid-svg-icons";

export enum IconKeys {
  Paste = "paste",
  Calendar = "calendar",
  Pager = "pager",
  Coffee = "coffee",
  Camera = "camera",
  Heart = "heart",
  Envelope = "envelope",
  Star = "star",
  Smile = "smile",
  Sun = "sun",
  Moon = "moon",
  Plane = "plane",
  Bicycle = "bicycle",
  Car = "car",
  Bus = "bus",
  Train = "train",
  Ship = "ship",
  Truck = "truck",
  Motorcycle = "motorcycle",
  CircleHalfStroke = "circleHalfStroke",
  Circle = "circle",
  CircleChecked = "circleChecked",
  Next = "next",
  Previous = "previous",
}

export const APP_ICONS = {
  [IconKeys.Paste]: faPaste,
  [IconKeys.Calendar]: faCalendar,
  [IconKeys.Pager]: faPager,
  [IconKeys.Coffee]: faCoffee,
  [IconKeys.Camera]: faCamera,
  [IconKeys.Heart]: faHeart,
  [IconKeys.Envelope]: faEnvelope,
  [IconKeys.Star]: faStar,
  [IconKeys.Smile]: faSmile,
  [IconKeys.Sun]: faSun,
  [IconKeys.Moon]: faMoon,
  [IconKeys.Plane]: faPlane,
  [IconKeys.Bicycle]: faBicycle,
  [IconKeys.Car]: faCar,
  [IconKeys.Bus]: faBus,
  [IconKeys.Train]: faTrain,
  [IconKeys.Ship]: faShip,
  [IconKeys.Truck]: faTruck,
  [IconKeys.Motorcycle]: faMotorcycle,
  [IconKeys.CircleHalfStroke]: faCircleHalfStroke,
  [IconKeys.Circle]: faCircle,
  [IconKeys.CircleChecked]: faCheckCircle,
  [IconKeys.Next]: faChevronRight,
  [IconKeys.Previous]: faChevronLeft,
};
